# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-21 21:16
from __future__ import unicode_literals

import account.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=200)),
                ('profile_email', models.CharField(max_length=200)),
                ('profile_amount', models.IntegerField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True, help_text='Want to say something to customer', max_length=500)),
                ('is_allowed', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=5, help_text='Enter amount in dollars')),
                ('drive_url', models.CharField(blank=True, max_length=200)),
                ('stripe_id', models.CharField(blank=True, max_length=120, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=account.models.upload_location)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=account.models.upload_location)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=account.models.upload_location)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=account.models.upload_location)),
                ('user', models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
