# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_charge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Charge',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='stripe_id',
            new_name='client_token',
        ),
        migrations.AddField(
            model_name='profile',
            name='customer_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
