# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 00:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190318_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 23, 17, 29, 7, 725642)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='amount',
            field=models.FloatField(default=5, help_text='Enter amount in dollars'),
        ),
    ]
