# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-21 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Time', models.TimeField()),
                ('Mail', models.EmailField(max_length=254)),
                ('ContactNumber', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('photographers_needed', models.IntegerField(null=True)),
                ('hours', models.IntegerField(null=True)),
                ('Description', models.TextField()),
                ('Mark_Completed', models.BooleanField()),
            ],
        ),
    ]
