# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-21 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='wao', help_text='upload ypur image', upload_to=main.models.upload_location)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField(help_text='introduce yourself')),
                ('skill1Name', models.CharField(help_text='Photoshop', max_length=200)),
                ('skill1Percentage', models.IntegerField()),
                ('skill2Name', models.CharField(help_text='Final Cut', max_length=200)),
                ('skill2Percentage', models.IntegerField()),
                ('skill3Name', models.CharField(help_text='Studio Photography', max_length=200)),
                ('skill3Percentage', models.IntegerField()),
                ('skill4Name', models.CharField(help_text='Motion Video', max_length=200)),
                ('skill4Percentage', models.IntegerField()),
                ('ShotsTaken', models.IntegerField()),
                ('CupsOfCoffe', models.IntegerField()),
                ('VideosEdited', models.IntegerField()),
                ('AwardsWon', models.IntegerField()),
                ('FacebookLink', models.CharField(help_text='Link of facebook profile', max_length=200, null=True)),
                ('VimeoLink', models.CharField(help_text='Link of vimeo profile', max_length=200, null=True)),
                ('InstagramLink', models.CharField(help_text='Link of instagram profile', max_length=200, null=True)),
                ('PinterestLink', models.CharField(help_text='Link of pinterest profile', max_length=200, null=True)),
                ('FlickLink', models.CharField(help_text='Link of pinterest profile', max_length=200, null=True)),
                ('Address', models.TextField(help_text='Address', max_length=200, null=True)),
                ('Mobile_number', models.CharField(help_text='Enter your phone/mobile number', max_length=200, null=True)),
                ('email', models.CharField(help_text='Address', max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'AboutMe',
                'verbose_name_plural': 'AboutMe',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, editable=False)),
                ('imageForSpecialties', models.ImageField(help_text='Image size should be 500X650', upload_to=main.models.upload_location)),
                ('imageForSlider', models.ImageField(help_text='Image for slider/coursel', upload_to=main.models.upload_location)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='PortfolioImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('large_image', models.ImageField(help_text='kindly upload the images having same size', upload_to=main.models.upload_location)),
                ('thumbnail_image', models.ImageField(help_text='upload small size images', upload_to=main.models.upload_location)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='main.Category')),
            ],
            options={
                'verbose_name': 'Portfolio_Images',
                'verbose_name_plural': 'Portfolio_Images',
            },
        ),
    ]
